name: Update IXP Data and Notify Webhook

on:
  schedule:
    # Runs "Every day at 00:00" (see https://crontab.guru)
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 5  # Corrected indentation here

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Packages
        run: |
           pip3 install beautifulsoup4
           pip3 install requests

      - name: Run get_peeringdb_ixps.py
        run: python3 get_peeringdb_ixps.py --output-peeringlan "${{ secrets.API_KEY_PEERINGDB }}"

      - name: Run get_he_ixps.py
        run: python3 get_he_ixps.py

      - name: Run get_pch_ixps.py
        run: python3 get_pch_ixps.py

      - name: Run merge_ixp_data.py
        run: python3 merge_ixp_data.py

      - name: Check for Changes
        id: check-changes
        run: |
          if git diff --quiet; then
            echo "No changes to data files"
            echo "::set-output name=no_changes::true"
          else
            echo "Changes detected"
            echo "::set-output name=no_changes::false"
          fi

      - name: Commit changes
        if: steps.check-changes.outputs.no_changes == 'false'
        uses: EndBug/add-and-commit@v9
        with:
          author_name: GitHub Workflow
          author_email: actions@github.com
          message: 'Updating IXPs'
          add: 'data/*.json'

      - name: Get Last Two Commits
        if: steps.check-changes.outputs.no_changes == 'false'
        id: get-commits
        run: |
          echo "LAST_COMMIT=$(git rev-parse HEAD)" >> $GITHUB_ENV
          echo "SECOND_LAST_COMMIT=$(git rev-parse HEAD~1)" >> $GITHUB_ENV

      - name: Generate Diff and Set Environment Variable
        if: steps.check-changes.outputs.no_changes == 'false'
        run: |
          git diff $SECOND_LAST_COMMIT $LAST_COMMIT -- data/ixps.json > diff_output.txt
          cat diff_output.txt

      - name: Send Update to Mattermost Channel
        run: |
          if [ "${{ steps.check-changes.outputs.no_changes }}" == "true" ]; then
            # No changes detected
            curl -X POST -H 'Content-type: application/json' --data "{ \"text\": \"No changes were detected in the latest automation run.\" }" "${{ secrets.MATTERMOST_WEBHOOK_URL }}"
          else
            # Changes detected, send git diff
            diff_content=$(cat diff_output.txt)
            json_payload=$(jq -R --slurp --arg codeblock "\`\`\`diff" --arg endcodeblock "\`\`\`" '{text: ($codeblock + "\n" + . + $endcodeblock)}' <<< "$diff_content")
            curl -X POST -H 'Content-type: application/json' --data "$json_payload" "${{ secrets.MATTERMOST_WEBHOOK_URL }}"
          fi
