name: Update IXP Data and Notify Webhook

on:
  schedule:
    # Runs "Every day at 00:00" (see https://crontab.guru)
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 5  # Corrected indentation here

      - name: test
        run: echo "test" >> data/ixps.json

      - name: Check for Changes
        id: check-changes
        run: |
          if git diff --quiet; then
            echo "No changes to data files"
            echo "NO_CHANGES=true" >> $GITHUB_ENV
          else
            echo "Changes detected"
            echo "NO_CHANGES=false" >> $GITHUB_ENV

      - name: Commit changes
        if: env.NO_CHANGES == 'false'
        uses: EndBug/add-and-commit@v9
        with:
          author_name: GitHub Workflow
          author_email: actions@github.com
          message: 'Updating IXPs'
          add: 'data/*.json'

      - name: Get Last Two Commits
        if: env.NO_CHANGES == 'false'
        id: get-commits
        run: |
          echo "LAST_COMMIT=$(git rev-parse HEAD)" >> $GITHUB_ENV
          echo "SECOND_LAST_COMMIT=$(git rev-parse HEAD~1)" >> $GITHUB_ENV
  
      - name: Generate Diff
        if: env.NO_CHANGES == 'false'
        id: generate-diff
        run: |
          diff=$(git diff $SECOND_LAST_COMMIT $LAST_COMMIT -- data/ixps.json)
          echo "::set-output name=diff::$diff"

      - name: Send Notification to Mattermost Channel
        if: env.NO_CHANGES == 'false'
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text": "```diff\n${{ steps.generate-diff.outputs.diff }}\n```"}' ${{ secrets.MATTERMOST_WEBHOOK_URL }}
