name: Update IXP Data and Notify Webhook

on:
  schedule:
    # Runs "Every day at 00:00" (see https://crontab.guru)
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 5  # Corrected indentation here

      - name: test
        run: echo "test" >> data/ixps.json

      - name: Check for Changes
        id: check-changes
        run: |
          if git diff --quiet; then
            echo "No changes to data files"
            echo "::set-output name=no_changes::true"
          else
            echo "Changes detected"
            echo "::set-output name=no_changes::false"
          fi

      - name: Commit changes
        if: steps.check-changes.outputs.no_changes == 'false'
        uses: EndBug/add-and-commit@v9
        with:
          author_name: GitHub Workflow
          author_email: actions@github.com
          message: 'Updating IXPs'
          add: 'data/*.json'

      - name: Get Last Two Commits
        if: steps.check-changes.outputs.no_changes == 'false'
        id: get-commits
        run: |
          echo "LAST_COMMIT=$(git rev-parse HEAD)" >> $GITHUB_ENV
          echo "SECOND_LAST_COMMIT=$(git rev-parse HEAD~1)" >> $GITHUB_ENV

      - name: Generate Diff and Set Environment Variable
        run: |
          git diff $SECOND_LAST_COMMIT $LAST_COMMIT -- data/ixps.json > diff_output.txt

      - name: Send Notification to Mattermost Channel
        run: |
          diff_content=$(cat diff_output.txt)
          json_payload=$(jq -R --slurp --arg codeblock "```diff" '{text: ($codeblock + "\n" + . + "\n```")}' <<< "$diff_content")
          curl -X POST -H 'Content-type: application/json' --data "$json_payload" ${{ secrets.MATTERMOST_WEBHOOK_URL }}
